# This is a basic workflow to help you get started with Actions

name: Build and test

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: INSTALL PREREQUISITES
      run: |
        echo ----------------- INSTALL PREREQUISITES ---------------------------------------------------
        sudo apt-get install python3-pip python3-setuptools
        pip3 install slither-analyzer
        cd proxy
        bash ./scripts/copy.sh
        yarn install
        npx buidler --version
        cd ../agent 
        npm install
        cd ../npms/skale-ima
        npm install
        cd ../..

    - name: MAIN OPERATIONS
      run: |
        echo ----------------- MAIN OPERATIONS ---------------------------------------------------
        npx ganache-cli --gasLimit 8000000 --quiet --acctKeys ../test/accounts.json &
        cd proxy
        yarn lint || travis_terminate 1
        slither --version
        slither . --filter-path openzeppelin-solidity,@openzeppelin/contracts/ || true            
        slither . --filter-path openzeppelin-solidity,@openzeppelin/contracts/ --exclude-informational --exclude reentrancy-events,constant-function,calls-loop,reentrancy-benign,pragma,assembly,blank-lines,timestamp,external-function,constable-states,locked-ether,solc-version,too-many-digits,shadowing-state,shadowing-local,uninitialized-state || travis_terminate 7
        yarn tslint || travis_terminate 2            
        yarn generate
        bash ./scripts/remove.sh
        RUNNING_NETWORK=test bash ./scripts/prepareSkaleManagerComponents.sh
        yarn test || travis_terminate 3
        cd ../test
        python3 ../scripts/config_from_accounts.py accounts.json config.json
        pip3 install -r requirements.txt
        python3 test.py || travis_terminate 6
        cd ../proxy
        npx buidler coverage --solcoverjs .solcover.js || travis_terminate 4
        cat coverage/lcov.info | npx codecov
        cd ..
